using System;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace QdratNew.Migrations
{
    /// <inheritdoc />
    public partial class FixCascadePathsForStudentRelations : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.AddColumn<bool>(
                name: "IsAIRecommended",
                table: "RemedialSessions",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<string>(
                name: "QuizType",
                table: "RemedialQuizzes",
                type: "nvarchar(max)",
                nullable: false,
                defaultValue: "");

            migrationBuilder.AddColumn<bool>(
                name: "AttendedInLab",
                table: "RemedialPlans",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsAutoGenerated",
                table: "RemedialPlans",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<bool>(
                name: "IsFree",
                table: "RemedialPlans",
                type: "bit",
                nullable: false,
                defaultValue: false);

            migrationBuilder.AddColumn<int>(
                name: "TriggerExamId",
                table: "RemedialPlans",
                type: "int",
                nullable: true);

            migrationBuilder.AddColumn<string>(
                name: "UniqueAccessCode",
                table: "RemedialPlans",
                type: "nvarchar(max)",
                nullable: true);

            migrationBuilder.AddColumn<int>(
                name: "IndicatorSectionId",
                table: "RemedialLessons",
                type: "int",
                nullable: true);

            migrationBuilder.CreateTable(
                name: "IndicatorRemedialCorrelations",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    StudentId = table.Column<int>(type: "int", nullable: false),
                    SectionId = table.Column<int>(type: "int", nullable: false),
                    PreRemedialScore = table.Column<double>(type: "float", nullable: false),
                    PostRemedialScore = table.Column<double>(type: "float", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_IndicatorRemedialCorrelations", x => x.Id);
                    table.ForeignKey(
                        name: "FK_IndicatorRemedialCorrelations_Sections_SectionId",
                        column: x => x.SectionId,
                        principalTable: "Sections",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_IndicatorRemedialCorrelations_Students_StudentId",
                        column: x => x.StudentId,
                        principalTable: "Students",
                        principalColumn: "StudentID",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "PerformanceIndicatorExams",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    CurriculumId = table.Column<int>(type: "int", nullable: false),
                    BatchId = table.Column<int>(type: "int", nullable: false),
                    Title = table.Column<string>(type: "nvarchar(150)", maxLength: 150, nullable: false),
                    QuestionsPerIndicator = table.Column<int>(type: "int", nullable: false),
                    DurationMinutes = table.Column<int>(type: "int", nullable: false),
                    PassPercent = table.Column<double>(type: "float", nullable: false),
                    CreatedAt = table.Column<DateTime>(type: "datetime2", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PerformanceIndicatorExams", x => x.Id);
                    table.ForeignKey(
                        name: "FK_PerformanceIndicatorExams_Batches_BatchId",
                        column: x => x.BatchId,
                        principalTable: "Batches",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_PerformanceIndicatorExams_Curriculums_CurriculumId",
                        column: x => x.CurriculumId,
                        principalTable: "Curriculums",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "PerformanceIndicatorExamSections",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    PerformanceIndicatorExamId = table.Column<int>(type: "int", nullable: false),
                    SectionId = table.Column<int>(type: "int", nullable: false),
                    QuestionCount = table.Column<int>(type: "int", nullable: false),
                    Score = table.Column<double>(type: "float", nullable: false)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_PerformanceIndicatorExamSections", x => x.Id);
                    table.ForeignKey(
                        name: "FK_PerformanceIndicatorExamSections_PerformanceIndicatorExams_PerformanceIndicatorExamId",
                        column: x => x.PerformanceIndicatorExamId,
                        principalTable: "PerformanceIndicatorExams",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_PerformanceIndicatorExamSections_Sections_SectionId",
                        column: x => x.SectionId,
                        principalTable: "Sections",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateTable(
                name: "StudentIndicatorResults",
                columns: table => new
                {
                    Id = table.Column<int>(type: "int", nullable: false)
                        .Annotation("SqlServer:Identity", "1, 1"),
                    StudentId = table.Column<int>(type: "int", nullable: false),
                    PerformanceIndicatorExamId = table.Column<int>(type: "int", nullable: false),
                    SectionId = table.Column<int>(type: "int", nullable: false),
                    ScorePercent = table.Column<double>(type: "float", nullable: false),
                    TakenAt = table.Column<DateTime>(type: "datetime2", nullable: false),
                    AverageTimePerQuestion = table.Column<double>(type: "float", nullable: true),
                    WasRushed = table.Column<bool>(type: "bit", nullable: false),
                    WasUnfocused = table.Column<bool>(type: "bit", nullable: false),
                    FailureReason = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_StudentIndicatorResults", x => x.Id);
                    table.ForeignKey(
                        name: "FK_StudentIndicatorResults_PerformanceIndicatorExams_PerformanceIndicatorExamId",
                        column: x => x.PerformanceIndicatorExamId,
                        principalTable: "PerformanceIndicatorExams",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Cascade);
                    table.ForeignKey(
                        name: "FK_StudentIndicatorResults_Sections_SectionId",
                        column: x => x.SectionId,
                        principalTable: "Sections",
                        principalColumn: "Id",
                        onDelete: ReferentialAction.Restrict);
                    table.ForeignKey(
                        name: "FK_StudentIndicatorResults_Students_StudentId",
                        column: x => x.StudentId,
                        principalTable: "Students",
                        principalColumn: "StudentID",
                        onDelete: ReferentialAction.Restrict);
                });

            migrationBuilder.CreateIndex(
                name: "IX_RemedialPlans_TriggerExamId",
                table: "RemedialPlans",
                column: "TriggerExamId");

            migrationBuilder.CreateIndex(
                name: "IX_RemedialLessons_IndicatorSectionId",
                table: "RemedialLessons",
                column: "IndicatorSectionId");

            migrationBuilder.CreateIndex(
                name: "IX_IndicatorRemedialCorrelations_SectionId",
                table: "IndicatorRemedialCorrelations",
                column: "SectionId");

            migrationBuilder.CreateIndex(
                name: "IX_IndicatorRemedialCorrelations_StudentId_SectionId",
                table: "IndicatorRemedialCorrelations",
                columns: new[] { "StudentId", "SectionId" });

            migrationBuilder.CreateIndex(
                name: "IX_PerformanceIndicatorExams_BatchId",
                table: "PerformanceIndicatorExams",
                column: "BatchId");

            migrationBuilder.CreateIndex(
                name: "IX_PerformanceIndicatorExams_CurriculumId",
                table: "PerformanceIndicatorExams",
                column: "CurriculumId");

            migrationBuilder.CreateIndex(
                name: "IX_PerformanceIndicatorExamSections_PerformanceIndicatorExamId",
                table: "PerformanceIndicatorExamSections",
                column: "PerformanceIndicatorExamId");

            migrationBuilder.CreateIndex(
                name: "IX_PerformanceIndicatorExamSections_SectionId",
                table: "PerformanceIndicatorExamSections",
                column: "SectionId");

            migrationBuilder.CreateIndex(
                name: "IX_StudentIndicatorResults_PerformanceIndicatorExamId",
                table: "StudentIndicatorResults",
                column: "PerformanceIndicatorExamId");

            migrationBuilder.CreateIndex(
                name: "IX_StudentIndicatorResults_SectionId",
                table: "StudentIndicatorResults",
                column: "SectionId");

            migrationBuilder.CreateIndex(
                name: "IX_StudentIndicatorResults_StudentId_SectionId",
                table: "StudentIndicatorResults",
                columns: new[] { "StudentId", "SectionId" });

            migrationBuilder.AddForeignKey(
                name: "FK_RemedialLessons_Sections_IndicatorSectionId",
                table: "RemedialLessons",
                column: "IndicatorSectionId",
                principalTable: "Sections",
                principalColumn: "Id");

            migrationBuilder.AddForeignKey(
                name: "FK_RemedialPlans_PerformanceIndicatorExams_TriggerExamId",
                table: "RemedialPlans",
                column: "TriggerExamId",
                principalTable: "PerformanceIndicatorExams",
                principalColumn: "Id");
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropForeignKey(
                name: "FK_RemedialLessons_Sections_IndicatorSectionId",
                table: "RemedialLessons");

            migrationBuilder.DropForeignKey(
                name: "FK_RemedialPlans_PerformanceIndicatorExams_TriggerExamId",
                table: "RemedialPlans");

            migrationBuilder.DropTable(
                name: "IndicatorRemedialCorrelations");

            migrationBuilder.DropTable(
                name: "PerformanceIndicatorExamSections");

            migrationBuilder.DropTable(
                name: "StudentIndicatorResults");

            migrationBuilder.DropTable(
                name: "PerformanceIndicatorExams");

            migrationBuilder.DropIndex(
                name: "IX_RemedialPlans_TriggerExamId",
                table: "RemedialPlans");

            migrationBuilder.DropIndex(
                name: "IX_RemedialLessons_IndicatorSectionId",
                table: "RemedialLessons");

            migrationBuilder.DropColumn(
                name: "IsAIRecommended",
                table: "RemedialSessions");

            migrationBuilder.DropColumn(
                name: "QuizType",
                table: "RemedialQuizzes");

            migrationBuilder.DropColumn(
                name: "AttendedInLab",
                table: "RemedialPlans");

            migrationBuilder.DropColumn(
                name: "IsAutoGenerated",
                table: "RemedialPlans");

            migrationBuilder.DropColumn(
                name: "IsFree",
                table: "RemedialPlans");

            migrationBuilder.DropColumn(
                name: "TriggerExamId",
                table: "RemedialPlans");

            migrationBuilder.DropColumn(
                name: "UniqueAccessCode",
                table: "RemedialPlans");

            migrationBuilder.DropColumn(
                name: "IndicatorSectionId",
                table: "RemedialLessons");
        }
    }
}
