using QdratNew.Entities;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace QdratNew.Entities{
    public class RemedialPlan
    {
        [Key]
        public int Id { get; set; }

        [ForeignKey("Student")]
        public int StudentID { get; set; }
        public Student Student { get; set; }

        [Required, StringLength(100)]
        public string Title { get; set; }

        [StringLength(500)]
        public string? Description { get; set; }

        public DateTime CreatedAt { get; set; } = DateTime.Now;
        public DateTime? StartDate { get; set; }
        public DateTime? EndDate { get; set; }

        // 🧩 عناصر الخطة الأساسية
        public string? WeakTopics { get; set; }
        public string? RecommendedMaterials { get; set; }

        public int? TotalSessions { get; set; }
        public int? CompletedSessions { get; set; }
        public int? TotalLessons { get; set; }
        public int? CompletedLessons { get; set; }

      
        public DateTime? UpdatedAt { get; set; }

        public bool? IsCompleted { get; set; } = false;

        public string? PerformanceLevel { get; set; }
        public string? Recommendations { get; set; }

        // نسبة الإنجاز المحسوبة
        [NotMapped]
        public double CompletionPercentage =>
            TotalLessons.HasValue && TotalLessons > 0
                ? Math.Round((CompletedLessons ?? 0) / (double)TotalLessons.Value * 100, 2)
                : 0;

        // الجلسات المرتبطة بالخطة
        public List<RemedialSession>? Sessions { get; set; } = new();

        // 🧠 حقول الذكاء الاصطناعي (اختيارية)
        public string? AISuggestedTopics { get; set; }
        public string? AIRecommendations { get; set; }
        public double? AIAssessedRiskScore { get; set; }
        public string? AIAssessedLevel { get; set; }

        // 🧾 الملاحظات التفاعلية
        public string? StudentFeedback { get; set; }
        public string? InstructorNotes { get; set; }

        // 🧩 الدروس العلاجية المرتبطة بالخطة
        public ICollection<RemedialLesson>? Lessons { get; set; }

        // 🧪 التقييم النهائي
        public int? FinalQuizId { get; set; }
        public RemedialQuiz? FinalQuiz { get; set; }

        // 🧠 بيانات منشأ الخطة
        public int? TriggerExamId { get; set; }
        public PerformanceIndicatorExam? TriggerExam { get; set; }

        public bool? IsAutoGenerated { get; set; } = false;
        public bool? IsFree { get; set; } = true;
        public bool? AttendedInLab { get; set; } = false;
        public string? UniqueAccessCode { get; set; }


        // ✅ ربط الخطة العلاجية بمحور محدد
        [ForeignKey("Section")]
        public int? SectionId { get; set; }  // نجعلها nullable لتجنب أخطاء التوافق مع البيانات القديمة
        public Section? Section { get; set; }

    }
}
