using Microsoft.EntityFrameworkCore;
using QdratNew.Data;
using QdratNew.Entities;
using QdratNew.Services.Interfaces;

namespace QdratNew.Services.Implementations
{
    public class PerformanceIndicatorAnalysisService : IPerformanceIndicatorAnalysisService
    {
        private readonly IDbContextFactory<ApplicationDbContext> _contextFactory;

        public PerformanceIndicatorAnalysisService(IDbContextFactory<ApplicationDbContext> contextFactory)
        {
            _contextFactory = contextFactory;
        }

        public async Task GenerateRemedialPlansAsync(int performanceExamId)
        {
            using var _context = _contextFactory.CreateDbContext();

            Console.WriteLine($"🧩 [DEBUG] بدأ تحليل الاختبار رقم {performanceExamId}");

            // 🟢 جلب بيانات الاختبار
            var exam = await _context.PerformanceIndicatorExams
                .AsNoTracking()
                .FirstOrDefaultAsync(e => e.Id == performanceExamId);

            if (exam == null)
            {
                Console.WriteLine("❌ لم يتم العثور على الاختبار.");
                return;
            }

            // 🧠 جلب نتائج الطلاب من جدول StudentIndicatorResults
            var studentResults = await _context.StudentIndicatorResults
                .Include(r => r.Section)
                .Where(r => r.PerformanceIndicatorExamId == performanceExamId)
                .ToListAsync();

            Console.WriteLine($"🔹 تم جلب {studentResults.Count} نتيجة طالب.");

            if (!studentResults.Any())
            {
                Console.WriteLine("⚠️ لا توجد نتائج طلاب لتحليلها.");
                return;
            }

            // 🧩 تجميع النتائج حسب الطالب
            var groupedByStudent = studentResults.GroupBy(r => r.StudentId).ToList();

            foreach (var group in groupedByStudent)
            {
                var studentId = group.Key;

                // 🟠 تحديد المحاور الضعيفة (أقل من 60%)
                var weakSections = group
                    .Where(r => r.ScorePercent < 60)
                    .Select(r => r.SectionId)
                    .Distinct()
                    .ToList();

                if (!weakSections.Any())
                {
                    Console.WriteLine($"✅ الطالب {studentId} لا يحتاج خطة علاجية.");
                    continue;
                }

                Console.WriteLine($"⚠️ الطالب {studentId} لديه {weakSections.Count} محور ضعيف.");

                // 🧩 التحقق من وجود خطة علاجية سابقة لنفس الطالب والاختبار
                var existingPlan = await _context.RemedialPlans
                    .FirstOrDefaultAsync(p => p.StudentID == studentId && p.TriggerExamId == performanceExamId);

                if (existingPlan != null)
                {
                    Console.WriteLine($"ℹ️ توجد خطة علاجية سابقة للطالب {studentId} لنفس الاختبار، سيتم تجاوزها.");
                    continue;
                }

                // ✅ إنشاء خطة علاجية جديدة ببيانات أساسية فقط
                var plan = new RemedialPlan
                {
                    StudentID = studentId,
                    Title = $"خطة علاجية لمؤشر الأداء: {exam.Title}",
                    Description = "خطة علاجية تلقائية من النظام بناءً على نتائج اختبار مؤشر الأداء.",
                    CreatedAt = DateTime.Now,
                    StartDate = DateTime.Now,
                    EndDate = DateTime.Now.AddDays(14),
                    TriggerExamId = exam.Id,
                    IsAutoGenerated = true,
                    IsFree = true,
                    IsCompleted = false,
                    PerformanceLevel = "ضعيف",
                    Recommendations = "راجع المحاور الضعيفة من خلال الدروس العلاجية.",
                    UniqueAccessCode = Guid.NewGuid().ToString("N").Substring(0, 8).ToUpper()
                };

                try
                {
                    _context.RemedialPlans.Add(plan);
                    await _context.SaveChangesAsync();
                    Console.WriteLine($"✅ تم إنشاء خطة علاجية جديدة للطالب {studentId} (Id: {plan.Id})");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"❌ خطأ أثناء حفظ RemedialPlan: {ex.InnerException?.Message ?? ex.Message}");
                    continue;
                }

                // 🟢 إنشاء جميع الدروس العلاجية دفعة واحدة لتحسين الأداء
                var lessonsToAdd = new List<RemedialLesson>();

                foreach (var sectionId in weakSections)
                {
                    var remedialLesson = new RemedialLesson
                    {
                        RemedialPlanId = plan.Id,
                        SectionId = sectionId,
                        Title = $"جلسة علاجية لمحور {sectionId}",
                        VideoUrl = null,
                        SupplementaryMaterial = string.Empty, // ✅ آمن ضد NULL
                        IsCompleted = false
                    };

                    remedialLesson.SupplementaryMaterial ??= string.Empty;
                    lessonsToAdd.Add(remedialLesson);
                }

                // ✅ إدخال جماعي لتقليل استعلامات SQL
                try
                {
                    _context.RemedialLessons.AddRange(lessonsToAdd);
                    await _context.SaveChangesAsync();

                    Console.WriteLine($"🟢 تم إنشاء {lessonsToAdd.Count} درس علاجي للطالب {studentId}");
                }
                catch (Exception ex)
                {
                    Console.WriteLine($"❌ خطأ أثناء حفظ دروس الطالب {studentId}: {ex.InnerException?.Message ?? ex.Message}");
                }
            }

            Console.WriteLine("🏁 [DEBUG] انتهى تنفيذ تحليل الاختبار بنجاح.");
        }
    }
}
