using Microsoft.EntityFrameworkCore;
using QdratNew.Data;
using QdratNew.Entities;
using QdratNew.Services.Interfaces;
using QdratNew.ViewModels.Remedial;

namespace QdratNew.Services.Implementations.Remedial
{
    public class RemedialPlanBuilderService : IRemedialPlanBuilderService
    {
        private readonly IDbContextFactory<ApplicationDbContext> _contextFactory;

        public RemedialPlanBuilderService(IDbContextFactory<ApplicationDbContext> contextFactory)
        {
            _contextFactory = contextFactory;
        }

        public async Task<int> GenerateSessionAsync(RemedialResourceSelectionVm model)
        {
            using var _context = _contextFactory.CreateDbContext();

            // 🧩 إنشاء خطة علاجية إن لم تكن موجودة
            var plan = await _context.RemedialPlans
                .Where(p => p.StudentID == model.StudentId)
                .OrderByDescending(p => p.CreatedAt)
                .FirstOrDefaultAsync();

            if (plan == null)
            {
                plan = new RemedialPlan
                {
                    StudentID = model.StudentId,
                    Title = $"خطة علاجية لمحور {model.SectionTitle}",
                    Description = "تم إنشاؤها تلقائيًا لإدارة جلسة علاجية بناءً على الأداء.",
                    CreatedAt = DateTime.Now,
                    StartDate = DateTime.Now,
                    EndDate = DateTime.Now.AddDays(14),
                    IsAutoGenerated = true,
                    IsFree = true
                };
                _context.RemedialPlans.Add(plan);
                await _context.SaveChangesAsync();
            }

            // 🧠 إنشاء جلسة علاجية جديدة
            var session = new RemedialSession
            {
                StudentID = model.StudentId,
                RemedialPlanId = plan.Id,
                LessonId = model.LessonId,
                CreatedAt = DateTime.Now,
                AccessCode = new Random().Next(100000, 999999).ToString(),
                IsCompleted = false
            };
            _context.RemedialSessions.Add(session);
            await _context.SaveChangesAsync();

            // 🎥 ربط الفيديوهات
            foreach (var vidId in model.SelectedVideoIds)
            {
                var videoUrl = await _context.RemedialVideos
                    .Where(v => v.Id == vidId)
                    .Select(v => v.VimeoUrl)
                    .FirstOrDefaultAsync();

                _context.RemedialLessons.Add(new RemedialLesson
                {
                    RemedialPlanId = plan.Id,
                    SectionId = model.SectionId,
                    VideoUrl = videoUrl,
                    IsCompleted = false
                });
            }

            // 🧩 ربط الأسئلة (اختبار مصغر)
            if (model.SelectedQuestionIds != null && model.SelectedQuestionIds.Any())
            {
                var quiz = new RemedialQuiz
                {
                    Title = $"اختبار تطبيقي بعد فيديو {model.LessonTitle}",
                    TotalQuestions = model.SelectedQuestionIds.Count,
                    QuizType = "Remedial"
                };
                _context.RemedialQuizzes.Add(quiz);
                await _context.SaveChangesAsync();

                foreach (var qid in model.SelectedQuestionIds)
                {
                    _context.RemedialQuizQuestions.Add(new RemedialQuizQuestion
                    {
                        RemedialQuizId = quiz.Id,
                        QuestionId = qid
                    });
                }
            }

            await _context.SaveChangesAsync();
            return session.Id;
        }
    }
}
